### ISSUE TITLE
Ma c'è qualcuno che riesce ad usare questo servizio IdP di test con successo?

### ISSUE THREAD

**Issue by alranel** [italia/spid-testenv#14]
_From @ncarandini on December 19, 2017 12:34_

Visto che ci sto perdendo davvero troppo tempo (rispetto a quanto preventivato) per far funzionare questo servizio di test, c'è qualcuno che può postare qui un file XML di una richiesta di Authn che una volta firmato e convertito in base64 funzioni col Request Validator?

_Copied from original issue: italia/spid-testenv-identityserver#12_

**Comment by alranel** [comment]
Chiudo perché ho visto che ti è stato risposto nel canale Slack

**Comment by ncarandini** [comment]
Si, aggiungo qui a beneficio di altri che abbiano lo stesso problema che la soluzione, almeno per il momento, è di non usare Edge ma di usare Chrome.
