### ISSUE TITLE
User list retrieved with no data

### ISSUE THREAD

**Issue by umbros** [italia/spid-testenv#16]
The user list is shown but without data
![image](https://user-images.githubusercontent.com/4085151/30836686-03a0adfe-a260-11e7-9cca-8a54156226f0.png)

**Comment by damikael** [comment]
Was the user created with the backoffice form?
Backoffice uses custom claims. Idp on master branch should be already updated with the right claims.

**Comment by damikael** [comment]
This is a record created from Backoffice:

![image](https://user-images.githubusercontent.com/31276401/30851840-18af558e-a2aa-11e7-840c-8502bfbdf42c.png)

**Comment by umbros** [comment]
If you restart the identity server and the backoffice u will see the problem

**Comment by damikael** [comment]
Restarted IS and the backoffice it works fine. Maybe latest commit solved the problem.
