### ISSUE TITLE
https richiesto per l'entity ID

### ISSUE THREAD

**Issue by alranel** [italia/spid-testenv#16]
_From @alexrj on November 5, 2017 21:29_

Il form di creazione di un Service Provider impone che l'entity ID inizi per `https`, ma secondo le regole tecniche è richiesto solo che sia una URI. L'ambiente di test quindi, se non erro, è più restrittivo delle regole tecniche e dovrebbe invece essere conforme.

_Copied from original issue: italia/spid-testenv-backoffice#18_

**Comment by alranel** [comment]
_From @damikael on November 7, 2017 11:43_

N.B. Avviso 6 (http://www.agid.gov.it/sites/default/files/documentazione/spid-avviso-n6-note-sul-dispiegamento-di-spid-presso-i-gestori-di-servizi-v1.pdf):

> entityid - Per garantire l’univocità si consiglia di usare il nome di dominio registrato dall’ente od un suo sottodominio (Avviso 6 par 2.2)

**Comment by alranel** [comment]
Sì, quel consiglio è chiaro. Ma questa mia segnalazione era relativa alla restrizione su `https`: una URI che inizia con `http` dovrebbe essere accettata.

**Comment by damikael** [comment]
Risolto con gli ultimi aggiornamenti. 
Sono ora accettate url anche in http.
