### ISSUE TITLE
Formato Location Single Logout Service e Assertion Consumer Service più restrittivo delle regole tecniche

### ISSUE THREAD

**Issue by alranel** [italia/spid-testenv#18]
L'interfaccia di backoffice impone che le URL usino `https`, che è un intento ovviamente lodevole ma se le regole tecniche non lo impediscono (mi sbaglio?) non è corretto che l'IdP di test sia più restrittivo. Peraltro in fase di sviluppo, magari con applicativi in locale, è facile che si lavori inizialmente senza TLS. Diversi framework non supportano HTTPS ma richiedono un reverse proxy, che in ambiente di sviluppo di solito non si ha. La mancanza di HTTPS dovrebbe essere un WARNING e non un errore bloccante, perché il sacrosanto obiettivo di incoraggiarne l'uso non dovrebbe andare a discapito della semplicità di sviluppo.
Se poi si dovesse aggiungere questa restrizione nelle regole tecniche (cosa sensata), lascerei questa cosa opzionale nel testenv per i motivi sopra detti ma applicherei la validazione all'accettazione dei metadati di produzione.

Inoltre l'hostname `localhost` non è ammesso, ma anche in questo caso non mi risulta nessun divieto nelle regole tecniche ed è molto frequente che si sviluppi in locale.

**Comment by alranel** [comment]
Inoltre vengono rifiutati tutti i TLD che hanno più di 4 caratteri.

**Comment by alranel** [comment]
Finché non viene corretto #22, è possibile bypassare la restrizione relativa a `https` e `localhost` semplicemente passando l'URL desiderato nel tag `<AssertionConsumerServiceURL>` della AuthnRequest.

**Comment by damikael** [comment]
Con gli ultimi rilasci l'interfaccia accetta url in https e http.
Corretta la validazione su TLD.
Accettato hostname localhost
