### ISSUE TITLE
Elencare l'Issuer al posto del Service Provider Name nella lista dei SP?

### ISSUE THREAD

**Issue by alranel** [italia/spid-testenv#21]
Nella "lista servizi" (che credo sia meglio rinominare in "Lista Service Provider" per usare una terminologia univoca) vengono elencati i valori che in WSO2 corrispondono al "Service Provider Name":

![schermata 2017-12-20 alle 16 39 32](https://user-images.githubusercontent.com/594957/34215009-61afd442-e5a4-11e7-99df-07e72f9aa962.png)

L'entity ID configurato nei metadati era `https://www.prova.it/`, valore che viene mantenuto da WSO2 come "Issuer" (ho verificato aprendo il pannello admin di WSO2) ma a quanto pare WSO2 genera un "Service Provider Name" applicando una trasformazione che apparentemente consiste nel togliere "https://". Questo valore non è molto utile, e per essere certo dell'Issuer mentre configuravo il mio SP ho dovuto appunto aprire WSO2. Credo sia meglio visualizzare l'Issuer anziché il "Service Provider Name".

**Comment by damikael** [comment]
Come consigliato, 
rinominato in "Lista Service Provider" 
mostrato l'issuer invece del service provider name di wso2
