### ISSUE TITLE
entityID incoerente

### ISSUE THREAD

**Issue by alranel** [italia/spid-testenv#24]
Usando il testenv in locale, i metadati esposti dal backoffice riportano:

```xml
<md:EntityDescriptor ... entityID="idp.spid.gov.it"> 
...
<md:SingleLogoutService ... Location="https://idp.spid.gov.it:9443/samlsso" ResponseLocation="https://idp.spid.gov.it:9443/samlsso"/> 
<md:SingleLogoutService ... Location="https://idp.spid.gov.it:9443/samlsso" ResponseLocation="https://idp.spid.gov.it:9443/samlsso"/> 
<md:SingleSignOnService ... Location="https://idp.spid.gov.it:9443/samlsso"/> 
<md:SingleSignOnService ... Location="https://idp.spid.gov.it:9443/samlsso"/> 
```

Vi sono alcuni problemi:

1. Secondo le Regole Tecniche l'attributo `entityID` dovrebbe essere una URI ma non lo è.
2. I tag `<SingleLogoutService>` e `<SingleSignOnService>`riportano un hostname non corrispondente con quello su cui gira il testenv (localhost o spid-testenv-identityserver).

Inoltre nelle asserzioni generate dal testenv si legge:

```xml
<saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity">spid-testenv-identityserver</saml2:Issuer>
```

Questa stringa è incoerente con i metadati di cui sopra e non è una URI come da Regole Tecniche.

**Comment by mlocati** [comment]
Vedere anche https://github.com/italia/spid-testenv-backoffice/pull/24 e https://github.com/italia/spid-testenv-identityserver/pull/13

**Comment by alexrj** [comment]
Da notare che se uso `spid-testenv-identityserver` nella `Destination` della Authnreqest WSO2 genera questo errore:

```
Destination validation for Authentication Request failed. Received: [spid-testenv-identityserver]. Expected one in the list: [https://spid-testenv-identityserver:9443/samlsso]
```

Quindi c'è una asimmetria tra il valore atteso per la `Destination` e il valore usato come `Issuer` nelle asserzioni, mentre secondo le Regole Tecniche dovrebbero coincidere (sbaglio?).
A questo punto l'unico modo per andare avanti è quello di disabilitare la validazione dell'`Issuer` nella mia implementazione SP, il che purtroppo mi sembra un comportamento insicuro da non incentivare.

**Comment by mlocati** [comment]
> 1 .Secondo le Regole Tecniche l'attributo entityID dovrebbe essere una URI ma non lo è.

Ho aggiornato italia/spid-testenv-backoffice#24 (vedi https://github.com/italia/spid-testenv-backoffice/pull/24/commits/dc4b7d3111511464a64568d254f6c41b93ba83cb ): ora l'entityID è un URL.

> 2. I tag `<SingleLogoutService>` e `<SingleSignOnService>` riportano un hostname non corrispondente con quello su cui gira il testenv (localhost o spid-testenv-identityserver).

Sempre in italia/spid-testenv-backoffice#24 ho corretto tale discordanza.

**Comment by damikael** [comment]
Risolto con https://github.com/italia/spid-testenv-backoffice/commit/4454cf701c2ff3dbdf9ba640fee6eb64c394d311
