### ISSUE TITLE
Non è possibile modificare il SingleLogoutService

### ISSUE THREAD

**Issue by alranel** [italia/spid-testenv#29]
Come riprodurre il problema:

1. Creare un nuovo Service Provider dall'interfaccia di backoffice, popolando il SingleLogoutService.
2. Tornare nuovamente al form di creazione, reinserendo tutti i dati uguali (in particolar modo l'entityID, così da sovrascrivere il Service Provider già creato).
3. Modificare il binding e/o la Location del SingleLogoutService.
4. Registrare il Service Provider.

A questo punto i valori modificati non saranno stati effettivamente recepiti, perché eseguendo un test di logout si nota come WSO2 continui ad usare il vecchio valore. Anche aprendo l'interfaccia admin di WSO2 si ritrova il vecchio valore.

**Comment by alranel** [comment]
Workaround verificato:

1. Accedere all'interfaccia admin di WSO2 e cancellare manualmente il Service Provider.
2. Accedere all'interfaccia di backoffice e procedere con la nuova creazione.

**Comment by damikael** [comment]
https://github.com/italia/spid-testenv-backoffice/commit/6ca47849ffa1f5bc8a43e7bf8e5d9f532075c991
Ad ogni salvataggio del service provider viene prima cancellato l'eventuale service provider già presente (avente lo stesso entityID)
