### ISSUE TITLE
Utilizzo con spid-sp-simplesamlphp

### ISSUE THREAD

**Issue by valerio-bozzolan** [italia/spid-testenv#3]
(Continuando https://github.com/italia/spid-sp-simplesamlphp/issues/12...)

Ciao!

Come si configura [spid-sp-simplesamlphp](https://github.com/italia/spid-sp-simplesamlphp) per funzionare con questo ambiente? :)

**Comment by alranel** [comment]
Ciao! Questa domanda è più appropriata sull'issue tracker di spid-sp-simplesamlphp oppure nel canale Slack #spid dove ci sono altri utenti che hanno usato SimpleSAMLphp.
Se nessuno ti sa rispondere vuol dire che serve aiuto dalla community per capire come si configura: ci aiuti tu? :)

**Comment by valerio-bozzolan** [comment]
OK. Sposto:

https://github.com/italia/spid-sp-simplesamlphp/issues/16
