### ISSUE TITLE
Le regole tecniche SPID non consentono il binding HTTP-Redirect per l'AssertionConsumerService

### ISSUE THREAD

**Issue by alranel** [italia/spid-testenv#33]
L'interfaccia di backoffice consente di impostare un AssertionConsumerService con binding HTTP-Redirect ma secondo le regole tecniche SPID è ammesso solo HTTP-POST. Credo sia opportuno togliere questa possibilità per evitare che uno sviluppatore possa fare una scelta implementativa che poi sarà potenzialmente incompatibile nell'ambiente di produzione.

![schermata 2018-01-05 alle 23 55 48](https://user-images.githubusercontent.com/594957/34632113-008e605c-f274-11e7-9e74-8ce8a37b3f39.png)

![schermata 2018-01-15 alle 00 32 23](https://user-images.githubusercontent.com/594957/34922112-b603346c-f98b-11e7-909e-6c6e53ed08a2.png)

**Comment by umbros** [comment]
Corretto e fa parte delle modifiche sulle regole. SAML permette sia binding post che redirect.

**Comment by alexrj** [comment]
Sono già uscite queste modifiche?

**Comment by alranel** [comment]
Non vedo commit che risolvono questa issue, e su https://idp.spid.gov.it:8080/ la situazione è rimasta come da segnalazione. È stato applicato un correttivo?

**Comment by damikael** [comment]
La commit https://github.com/italia/spid-testenv-backoffice/commit/d5f8206d91cbdc24d8eca2e5f2b915a54157ae6a risolve l'adeguamento alle regole tecniche

**Comment by damikael** [comment]
A seguito di chiarimento con @umbros il binding in HTTP-REDIRECT viene consentito
