### ISSUE TITLE
Error when processing theauthentication request

### ISSUE THREAD

**Issue by giafar** [italia/spid-testenv#36]
Salve,
facendo un test con il service provider che stiamo collaudando ed utilizzando l'idp di test riceviamo il messaggio in oggetto: test effettuato alle 21:49 di oggi.
Abbiamo verificato i valori passati in input all'IDP tramite i tool riportati a questo [link](https://www.samltool.com/validate_authn_req.php) e sembrano validi. Potete, cortesemente, indicarci se riscontrate problematica lato IDP ? La stessa configurazione dell'SP sull'IDP spid-testenv-identityserver in container docker funziona correttamente.

*SAML Auth Request*
```
lVNNa+MwEL33Vxjd4+9sExEHQsJCoF3aZtnDXopqT1KBPlzNuEn/fWUlzRraBtYnMfM0783T8wyFVi1fdPRsHuClA6TooJVBHhoV65zhVqBEboQG5FTzzeL2hudxyltnydZWsWiBCI6kNUtrsNPgNuBeZQ1r08ChYplHEDn51BEcEdLsPkFWnlwa0Y+p2DNRizxJZNPG2Mom3tnXWBKflmWR9NoQLYt+WldDEB8mrFcVe4RJMZ1c1wDwQ2zzcVoX07wcl9kYrqEpnsYehth5XiRhqGJ5mk1GaTbKst95ysuSZ8VfFv0Bh0GIX5QNLLnsiPjwgc2voi++WT+CB37Xi9eCLg/sK7IZbQOUgyFJbyz65av3nVByK8H98wrbGA5Ctwpi63bBJV9j88v9WTIQ9Vn27JiQnnK9urNK1m/RQim7XzoQBMH3/9+EnDAo/T4smZ8YTvGDJrynjwnBgaKl1a1wEvun8KmRutPseIMPcUvlrX+A7XnX/X4/zE2y8eeb7LTrlzePvW90nLvDP2X+Dg==
```
*SP entityId*
```
https://sp.example.org/saml/sp
```
*Target URL, Destination of the AuthN Request*
```
https://idp.spid.gov.it:9443/samlsso
```
*X.509 cert of the Service Provider*
```
MIIDUDCCAjgCCQDZCqTq9PxalzANBgkqhkiG9w0BAQsFADBlMQswCQYDVQQGEwJJ
VDEPMA0GA1UECAwGSXRhbGlhMQ0wCwYDVQQHDARSb21hMRgwFgYDVQQKDA9UZXN0
IFNoaWJib2xldGgxDTALBgNVBAsMBFRlc3QxDTALBgNVBAMMBFRlc3QwHhcNMTcx
MjI5MTQ1NTI2WhcNMTkwNTEzMTQ1NTI2WjBvMQswCQYDVQQGEwJJVDEPMA0GA1UE
CAwGSXRhbGlhMQ0wCwYDVQQHDARSb21hMRgwFgYDVQQKDA9UZXN0IFNoaWJib2xl
dGgxDTALBgNVBAsMBFRlc3QxFzAVBgNVBAMMDnNwLmV4YW1wbGUub3JnMIIBIjAN
BgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxerukal82KtS9f/zZmQ9ojfEP+gw
shv1S4HuWLXu81Y55RjX//SpvehJYIwAsXqTkGyHJ1Azi8bz2HZo3+zpphvDXYX8
APX17+XEcPszaNGvY+LMEhZbsw/3X9iVW3/eNppy7KJi8LrcFo0Xid8oDQN+p2Ix
lpdWZOSKYDA9U4r43BnYzSRFkIkgCFJE0nGJKBLRCGIBl1onSz/6mQYKIrZodmhR
jlxDFDoHZLLVv7pact75idWSvR8UnA/vd//QoraCEB7sSLj5C0u4aeKTmMI3U84s
eIYE4tNAmiFfvvU37mmmtaG/7ddIhC9CakVo7gwlxzTyCR9EBlD9miCnJQIDAQAB
MA0GCSqGSIb3DQEBCwUAA4IBAQBZVIIv8Ngabu0pNuvk6gVZpq8/r7KKue+ICcR5
x9LIf+sKPOllvEvL17iFhG2ggNzYIa4mxpM6EJV9ZqGAZhXTSrO+7fg5bNEPPtZ8
pbFxlUWXSBVoSaH2SwHMUIbjZPf5poPom7AInuEHIaKqbJkQ7vERGarxCZ01Jens
hNL6463qG+dvmIKn4ydu7tSNQei4ZoKbMgFMFsjEOWr4CWyEivXcoFGKDMDWpFx6
38tHq5M/tGc0Vvlx/kuIvj9a/k1ku06w98fcxPScB1V3pwc9eCpnGornoDhljfiO
klEP51sP3GDRcceIsRupEmLZCQc784boU2E7doA4+2lkAmYE
```
*Signature of the SAML AuthN Request*
```
tj+6QQoHlX6yUem5KObVH4P1PP9MP3iTol5NZFmUbKEj2SgKCr3ZZn2Uh/+bmsHpGyc2+TP+z+AztGNlCapbviZnByLorJkrOQI2dTYWXStmCGzsWRZL3drtY8oKw8MI4kr/E/D3WjZg9KnTvRE7rQbne+l+ZA+0bZkIZdAnF/uaism7EqVk3Ogl+oqk+6ejQidCI+gRlcuamMWYVZHzVK9d+rya0zwoUu+bi+AOGywlfiD2ohH8TtjU/tX17SFhtjyHjfpP5orubnNWTLZA1++g1TUW67mUWxcad/XMNldrWQwwWqeibl7+4uznO+jwCFdJKwnd5DvU5pz1R77PPw==
```
*RelayState*
```
ss:mem:8de6b49a7908095b1c698a71390a0b559e0670bbdba157353e8efa626f4400de
```
*SigAlg*
```
http://www.w3.org/2001/04/xmldsig-more#rsa-sha256
```
*Di seguito riportiamo anche la request in formato xml*
```
<?xml version="1.0"?>
<samlp:AuthnRequest xmlns:samlp="urn:oasis:names:tc:SAML:2.0:protocol" xmlns:saml="urn:oasis:names:tc:SAML:2.0:assertion" AssertionConsumerServiceIndex="1" AttributeConsumingServiceIndex="1" Destination="https://idp.spid.gov.it:9443/samlsso" ForceAuthn="1" ID="_e83987ceee6af250c39245415e7ed3b5" IssueInstant="2018-01-11T20:44:13Z" Version="2.0">
  <saml:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" NameQualifier="https://sp.example.org/saml/sp">https://sp.example.org/saml/sp</saml:Issuer>
  <samlp:NameIDPolicy AllowCreate="1" Format="urn:oasis:names:tc:SAML:2.0:nameid-format:transient"/>
  <samlp:RequestedAuthnContext Comparison="minimum">
    <saml:AuthnContextClassRef>https://www.spid.gov.it/SpidL1</saml:AuthnContextClassRef>
  </samlp:RequestedAuthnContext>
</samlp:AuthnRequest>
```
**Risposta del tool**
```
THE SAML AUTHN REQUEST IS VALID
```

Grazie in anticipo.

**Comment by damikael** [comment]
Salve, potreste verificare nuovamente.
Assicurarsi di aver registrato il proprio sp tramite l'interfaccia di backoffice disponibile all'indirizzo https://idp.spid.gov.it:8080 e di aver configurato il proprio sp con i dati dell'idp di test. In particolare:

SingleSignOnService Location:
**https://idp.spid.gov.it/samlsso**

SingleLogoutService Location:
**https://idp.spid.gov.it/samlsso**

NameIDFormat:
**urn:oasis:names:tc:SAML:2.0:nameid-format:transient**

X509Certificate:
**MIICNTCCAZ6gAwIBAgIES343gjANBgkqhkiG9w0BAQUFADBVMQswCQYDVQQGEwJVUzELMAkGA1UE
CAwCQ0ExFjAUBgNVBAcMDU1vdW50YWluIFZpZXcxDTALBgNVBAoMBFdTTzIxEjAQBgNVBAMMCWxv
Y2FsaG9zdDAeFw0xMDAyMTkwNzAyMjZaFw0zNTAyMTMwNzAyMjZaMFUxCzAJBgNVBAYTAlVTMQsw
CQYDVQQIDAJDQTEWMBQGA1UEBwwNTW91bnRhaW4gVmlldzENMAsGA1UECgwEV1NPMjESMBAGA1UEAwwJbG9jYWxob3N0MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCUp/oV1vWc8/TkQSiAvTou
sMzOM4asB2iltr2QKozni5aVFu818MpOLZIr8LMnTzWllJvvaA5RAAdpbECb+48FjbBe0hseUdN5
HpwvnH/DW8ZccGvk53I6Orq7hLCv1ZHtuOCokghz/ATrhyPq+QktMfXnRS4HrKGJTzxaCcU7OQID
AQABoxIwEDAOBgNVHQ8BAf8EBAMCBPAwDQYJKoZIhvcNAQEFBQADgYEAW5wPR7cr1LAdq+IrR44i
QlRG5ITCZXY9hI0PygLP2rHANh+PYfTmxbuOnykNGyhM6FjFLbW2uZHQTY1jMrPprjOrmyK5sjJR
O4d1DeGHT/YnIjs9JogRKv4XHECwLtIVdAbIdWHEtVZJyMSktcyysFcvuhPQK8Qc/E/Wq8uHSCo=**


Per ulteriore supporto è possibile inviare un ticket su https://helpdesk.spid.gov.it/ alla categoria "Supporto ambiente di test"

Grazie

**Comment by giafar** [comment]
Ciao @damikael ,
ora la response arriva, abbiamo aggiornato il metadata.xml all'ultima versione disponibile, ma riceviamo un errore sul service provider perché lo issuer non è corretto.
Nella response riceviamo
```
<saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">idp.spid.gov.it</saml2:Issuer>
```
ma dovrebbe corrispondere all'entity id dell'IDP che è https://idp.spid.gov.it e non idp.spid.gov.it
```
<saml2:Issuer Format="urn:oasis:names:tc:SAML:2.0:nameid-format:entity" xmlns:saml2="urn:oasis:names:tc:SAML:2.0:assertion">https://idp.spid.gov.it</saml2:Issuer>
```
e quindi l'SP non è in grado di identificare l'IDP.

A disposizione per ulteriori test.

Saluti Gianluca.

**Comment by damikael** [comment]
L'IdP restituisce ora l'issuer corretto.
