### ISSUE TITLE
Il tag AssertionConsumerService viene generato in maniera non conforme alle regole tecniche

### ISSUE THREAD

**Issue by alranel** [italia/spid-testenv#38]
Le Regole Tecniche prescrivono quanto segue:

![schermata 2018-01-15 alle 00 36 35](https://user-images.githubusercontent.com/594957/34922150-4cdfbf40-f98c-11e7-9fef-40e380ef6fbc.png)

Tuttavia inserendo più `AssertionConsumerService` il backoffice consente di impostare il secondo come default, contravvenendo alle Regole Tecniche (non ho controllato cosa prescriva SAML):

![schermata 2018-01-15 alle 00 35 19](https://user-images.githubusercontent.com/594957/34922172-9996bb5e-f98c-11e7-835d-cab9918e4495.png)

(Mi pare chiaro che quando le regole parlano del _primo_ elemento si riferiscono all'ordine nell'XML; se invece fosse un modo per dire "il principale AssertionConsumerService desiderato" la prescrizione su `index` sarebbe tautologica per cui mi sento di escludere questa interpretazione delle Regole...)

**Comment by damikael** [comment]
Corretto l'ordine di presentazione dell'elemento Default nell'xml
https://github.com/italia/spid-testenv-backoffice/commit/a2888ad79c1e5ce11fe0a6c18e7db1c7565f4613
