### ISSUE TITLE
authnContextClassRef non corretta

### ISSUE THREAD

**Issue by giafar** [italia/spid-testenv#42]
Salve,
riscontro un problema sull'identity provider di test, https://idp.spid.gov.it, in quanto a fronte di una authnContextClassRef di tipo https://www.spid.gov.it/SpidL1 viene restituita urn:oasis:names:tc:SAML:2.0:ac:classes:Password non richiesta dall'SP e per questo le assertion non vengono assegnate alla sessione anche se l'utente risulta correttamente autenticato.

Grazie in anticipo.

**Comment by alranel** [comment]
Duplicato di #26, chiudo questa :)
