### ISSUE TITLE
spidCode non conforme alle specifiche

### ISSUE THREAD

**Issue by flistell** [italia/spid-testenv#43]
La [tabella attributi](http://www.agid.gov.it/sites/default/files/regole_tecniche/tabella_attributi_idp_v1_0.pdf) specifica che per spidCode il formato è il seguente:   

    <codice Identificativo> = <cod_IdP><nr. univoco> 

Dove: 
 * `<cod_IdP>`: è un codice  composto da 4 lettere univocamente    assegnato  al  gestore  delle 
identità; 
 * `<nr.univoco>`:  è  una  stringa  alfanumerica composta da 10 caratteri che il   gestore delle identità genera in maniera univoca nell’ambito del proprio dominio. 

Lo `spidCode` rilasciato dall'IDP di test invece è uno UUID:

```xml
<saml2:Attribute Name="spidCode" NameFormat="urn:oasis:names:tc:SAML:2.0:attrname-format:basic">
    <saml2:AttributeValue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:type="xs:string">d22660e6-c518-4e72-ac5d-354b6cab307c</saml2:AttributeValue>
</saml2:Attribute>
```

**Comment by damikael** [comment]
Con l'ultimo aggiornamento lo spidCode è conforme alle specifiche. 
<cod_IdP> per l'ambiente di test è "TEST"

Grazie per la segnalazione.
