### ISSUE TITLE
fiscalNumber non conforme alle specifiche

### ISSUE THREAD

**Issue by flistell** [italia/spid-testenv#44]
La [tabella attributi](http://www.agid.gov.it/sites/default/files/regole_tecniche/tabella_attributi_idp_v1_0.pdf) specifica che per fiscalNumber il formato è il seguente:   

    <fiscalNumber> = TINIT-<codice fiscale> 

L'interaccia di backoffice invece richiede l'inserimento del Codice Fiscale che viene poi inserito nell'asserzione così come viene inserito, ovvero senza prefisso.

Naturalmente, per aggirare il problema, è possibile inserire nell'interfaccia di backoffice il codice fiscale in formato "spid" dato che nessun controllo di validazione viene fatto.

**Comment by damikael** [comment]
Con l'ultimo aggiornamento i codici fiscali sono salvati sull'IDP con il prefisso "TINIT-" così da essere restituiti secondo il formato atteso.
Ambiente di test online allineato.

Grazie per la segnalazione.
