### ISSUE TITLE
Contextual help in SP creation form

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv#6]
* Add question mark buttons and/or `help-block` paragraphs in the form with friendlier explanation of form fields.

**Comment by umbros** [comment]
Done! Added contextual help and attribute divided by components (ex: doc id is divided by number, date...)
![image](https://user-images.githubusercontent.com/4085151/30787819-fa6b7f4e-a191-11e7-9b65-44a01637a535.png)

**Comment by umbros** [comment]
Done! Added contextual help and attribute divided by components (ex: doc id is divided by number, date...)
![image](https://user-images.githubusercontent.com/4085151/30787847-700fb95e-a192-11e7-8cd7-97603c15dbec.png)
