### ISSUE TITLE
Errori nella creazione degli utenti

### ISSUE THREAD

**Issue by alexrj** [italia/spid-testenv#8]
La prima creazione di un utente è andata a buon fine, ma il form non si è svuotato. Inviandolo una seconda volta (senza fare modifiche ai valori) viene creato un ulteriore utente con dati sbagliati:

![schermata 2017-09-24 alle 21 49 23](https://user-images.githubusercontent.com/594957/30786174-42b75d56-a172-11e7-9d0e-2df8cbd54993.png)

**Comment by alexrj** [comment]
Inoltre in nessuno dei due invii ha salvato il codice fiscale che avevo inserito nel form ("xxxx").

**Comment by damikael** [comment]
Risolto con gli ultimi aggiornamenti
